// chp5q3

try {
  let a = heloo;
} catch (e) {
  //used to handle erros
  console.log(e.name);
  console.log(e.message);
} finally {
  //this block will always execute
  console.log("excecuted...");
}
